server:
  port: 5503
  host: localhost
auth:
  jwksUri: http://localhost:8000/api/auth/.well-known/jwks.json
database:
  url: mongodb+srv://gauravpadwal48:XeLVXGbeppDn7PUP@cluster0.xhiek.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster0
kafka:
  broker: localhost:9092